name: CI-iOS

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.app

    - name: Run tests
      run: xcodebuild clean build test -workspace RookBook/RookBook.xcworkspace -scheme "CI-iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 16,OS=18.0" ONLY_ACTIVE_ARCH=YES -resultBundlePath iOSResults -derivedDataPath /tmp/XcodeDerivedDataWithCoverage

    # 3rd party script for showing result in Github Actions screen
    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: iOSResults.xcresult
      if: success() || failure()