name: CI-macOS

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-14
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.0.app

    - name: Run tests
      run:  xcodebuild clean build test -project  RookBook/RookBookCore.xcodeproj -scheme "CI-macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES -resultBundlePath macOSResults -derivedDataPath /tmp/XcodeDerivedDataWithCoverage
    
    - name: Upload xcresult file
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
          name: macOSResults-${{ github.run_number }}.xcresult
          path: macOSResults.xcresult
